version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    ignore:                                      # バージョンアップの除外設定
      - dependency-name: actions/upload-artifact # 除外する依存関係の名前
        versions:                                # 除外対象のバージョン
          - 4.3.0
          - 4.3.1
      - dependency-name: 'actions/*'             # アスタリスクは任意文字列にマッチ
        update-types:                            # 除外するバージョンアップの種類
          - version-update:semver-major
