name: Cross repo
on: push
env:
  TARGET_REPO: another-repo # GitHub Appsのインストール時に設定したリポジトリ
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - id: create                                 # GitHub Appsトークンの生成
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: ${{ env.TARGET_REPO }}
      - uses: actions/checkout@v4                  # 別リポジトリのチェックアウト
        with:
          repository: ${{ github.repository_owner }}/${{ env.TARGET_REPO }}
          path: ${{ env.TARGET_REPO }}
          token: ${{ steps.create.outputs.token }}
      - run: cat "${TARGET_REPO}/README.md"        # 別リポジトリのREADMEを表示
